language: node_js
node_js: "8"
before_script:
  - npm install -g gulp-cli
  - npm install
script:
  - gulp production-min
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist/
  repo: https://$DT_DEPLOY_USERNAME:$DT_DEPLOY_PASSWORD@DbugTech/dbugtech.github.io?cname=dbugtech.com
  github-token: $MAROOF_PERSONAL_ACCESS_TOKEN
  keep-history: true
  on:
    branch: master